# Generated by Django 5.0.6 on 2024-05-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='answers',
        ),
        migrations.AddField(
            model_name='answermodel',
            name='question',
            field=models.ManyToManyField(to='question.questionmodel'),
        ),
    ]
