# Generated by Django 5.0.6 on 2024-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_answermodel_question_answermodel_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='question.tagmodel'),
        ),
    ]
