# Generated by Django 5.0.6 on 2024-05-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_tagmodel_questionmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
