# Generated by Django 5.0.6 on 2024-05-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_tagmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='slug',
            field=models.SlugField(auto_created=True, default='', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
