# Generated by Django 5.0.6 on 2024-05-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profilemodel_bio_profilemodel_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
